// scripts/prevent-proto2.js
// Node.js fallback script in case the sh executing environment lacks grep
const { execSync } = require('child_process');

try {
    const stagedFiles = execSync('git diff --cached --name-only').toString();
    if (stagedFiles.includes('proto2.html')) {
        console.error('\n🚨 [PRE-COMMIT ERROR] You are trying to commit proto2.html directly!');
        console.error('proto2.html is generated by CI/CD automatically. Please edit source files instead.');
        console.error('To resolve this, run: git restore --staged proto2.html\n');
        process.exit(1);
    }
} catch (err) {
    // If git diff fails (e.g. no commits yet), ignore
}
