// scripts/setup-hooks.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const hookDir = path.resolve(__dirname, '..', '.git', 'hooks');
const preCommitPath = path.join(hookDir, 'pre-commit');

// Create hooks directory if missing
if (!fs.existsSync(hookDir)) {
    try { fs.mkdirSync(hookDir, { recursive: true }); }
    catch (e) { /* ignore */ }
}

const hookScript = `#!/bin/sh
# proto2.html is a build output. Do NOT commit it.
if git diff --cached --name-only | grep -q "proto2\\.html"; then
  echo ""
  echo "🚨 [PRE-COMMIT ERROR] You are trying to commit proto2.html directly!"
  echo "proto2.html is generated by CI/CD automatically. Please edit index.html or source files instead."
  echo "To resolve this, run: git restore --staged proto2.html"
  echo ""
  exit 1
fi
`;

try {
    fs.writeFileSync(preCommitPath, hookScript, { mode: 0o755 });
    console.log("✅ Git pre-commit hook installed successfully.");
} catch (err) {
    console.warn("⚠️ Could not install pre-commit hook automatically:", err.message);
}
